workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - cm_vj
      vars:
        java: 17
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease
      - name: Build Android release II
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
